import { Gantari } from "next/font/google";
import "./globals.css";

const gantariFont = Gantari({
  subsets: ["latin"],
  weight: "800",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${gantariFont.className}  antialiased`}>
        {children}
      </body>
    </html>
  );
}
